FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /users-server ./cmd/users-server

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=builder /users-server /users-server

EXPOSE 8082

USER nonroot:nonroot

ENTRYPOINT ["/users-server"]
