#!/usr/bin/env python3
"""Generate a curated changelog draft from recent non-merge commits."""

from __future__ import annotations

import argparse
import json
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List


@dataclass
class Commit:
    sha: str
    short_sha: str
    date: str
    subject: str


SECTION_RULES = [
    ("dependencies", ["deps", "dependabot", "bump", "upgrade", "update " ]),
    ("docs", ["docs", "readme", "checklist", "changelog"]),
    ("fixed", ["fix", "bug", "error", "regression", "retry", "rollback"]),
    ("changed", ["add", "implement", "refactor", "improve", "update", "wire", "enable"]),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate CHANGELOG.md draft section")
    parser.add_argument("--repo", default=".", help="Repository root path")
    parser.add_argument("--max", type=int, default=30, help="Max non-merge commits")
    parser.add_argument("--since", default="", help="Optional git --since filter (example: 30 days ago)")
    parser.add_argument("--out", default="", help="Optional output markdown path")
    return parser.parse_args()


def run_git_log(repo: Path, max_commits: int, since: str) -> List[Commit]:
    pretty = "%H%x1f%h%x1f%ad%x1f%s"
    cmd = ["git", "log", "--no-merges", f"--pretty=format:{pretty}", "--date=short", f"-n{max_commits}"]
    if since.strip():
        cmd.append(f"--since={since.strip()}")

    proc = subprocess.run(cmd, cwd=repo, capture_output=True, text=True, check=True)
    commits: List[Commit] = []
    for line in proc.stdout.splitlines():
        parts = line.split("\x1f")
        if len(parts) != 4:
            continue
        sha, short_sha, date, subject = parts
        commits.append(Commit(sha=sha, short_sha=short_sha, date=date, subject=subject.strip()))
    return commits


def section_for_subject(subject: str) -> str:
    lowered = subject.lower().strip()
    for name, needles in SECTION_RULES:
        if any(token in lowered for token in needles):
            return name
    return "changed"


def to_bullet(commit: Commit) -> str:
    return f"- {commit.subject} (`{commit.short_sha}`)"


def should_skip(subject: str) -> bool:
    lowered = subject.strip().lower()
    if lowered.startswith("http://") or lowered.startswith("https://"):
        return True
    if "youtube.com/" in lowered or "youtu.be/" in lowered:
        return True
    return False


def render(commits: List[Commit], max_commits: int, since: str) -> str:
    sections: Dict[str, List[str]] = {"fixed": [], "changed": [], "dependencies": [], "docs": []}
    skipped = 0
    for commit in commits:
        if should_skip(commit.subject):
            skipped += 1
            continue
        sections[section_for_subject(commit.subject)].append(to_bullet(commit))

    lines = [
        "# Changelog Draft",
        "",
        "## Unreleased",
        "",
        f"Generated from last `{max_commits}` non-merge commits" + (f" since `{since}`." if since else "."),
        "",
    ]

    for title, key in [("Fixed", "fixed"), ("Changed", "changed"), ("Dependencies", "dependencies"), ("Docs", "docs")]:
        if not sections[key]:
            continue
        lines.append(f"### {title}")
        lines.append("")
        lines.extend(sections[key])
        lines.append("")

    if not commits:
        lines.extend(["- No non-merge commits found for the selected filters.", ""])

    lines.append(f"_Generated by `scripts/changelog_draft.py` (skipped {skipped} non-curated commit subject(s))._")
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    repo = Path(args.repo).resolve()
    commits = run_git_log(repo=repo, max_commits=args.max, since=args.since)
    markdown = render(commits=commits, max_commits=args.max, since=args.since)

    if args.out.strip():
        out_path = Path(args.out)
        if not out_path.is_absolute():
            out_path = (repo / out_path).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(markdown, encoding="utf-8")
        print(f"Wrote changelog draft to: {out_path}")
    else:
        print(markdown)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
